

services:
  auth-service:
    container_name: auth-service-c  # Container name for the auth service
    build:
      context: .
    image: auth-service-i  # Image name
    ports:
      - "5002:5002"  # Host port 5002 -> Container port 5002
    networks:
      - epma-network
    restart: always

networks:
  epma-network:
    external: true
